version: "3"

tasks:
  prepare:
    desc: Prepare the environment
    cmds:
      - npm i

  build:
    deps: [prepare]
    dir: school-module
    desc: Build the school module
    cmds:
      - npm i
      - npx tsc

  watch:
    deps: [prepare]
    dir: school-module
    desc: Watch the school module and build on changes
    cmds:
      - npm i
      - npx tsc -w

  up:
    deps: [build]
    desc: Start the Connector
    cmds:
      - docker compose up -d

  restart:
    desc: Restart the Connector
    cmds:
      - docker compose restart connector

  logs:
    desc: Show Connector logs
    cmds:
      - docker compose logs -f connector

  create-student:
    desc: Call the create-student endpoint
    cmds:
      - 'echo -n ''{"pin": "1234", "givenname": "Max", "surname": "Mustermann", "additionalConsents": [{"title": "aTitle", "consent": "A Consent Bla", "link": "https://example.com"}]}'' | http -b POST localhost:8099/students/{{.STUDENT_ID}} ''X-API-KEY: This_is_a_test_APIKEY_with_30_chars+'' | echo "$(jq -r ''.result.qrContent'')" | qrencode -t ansiutf8'
    requires:
      vars: [STUDENT_ID]

  get-student:
    desc: Call the get-student endpoint
    cmds:
      - "http -b GET localhost:8099/students/{{.STUDENT_ID}} 'X-API-KEY: This_is_a_test_APIKEY_with_30_chars+' | jq"
    requires:
      vars: [STUDENT_ID]

  get-students:
    desc: Call the get-students endpoint
    cmds:
      - "http -b GET localhost:8099/students 'X-API-KEY: This_is_a_test_APIKEY_with_30_chars+' | jq"

  send-file:
    desc: Call the send-file endpoint
    cmds:
      - 'echo -n ''{"file": "{{.FILE_BASE64}}", "filename": "Abiturzeugnis.pdf", "mimetype": "application/pdf"}'' | http -b POST localhost:8099/students/{{.STUDENT_ID}}/files ''X-API-KEY: This_is_a_test_APIKEY_with_30_chars+'' | jq'
    vars:
      FILE_BASE64:
        sh: "cat assets/Zeugnis.pdf | base64 -w 0"
    requires:
      vars: [STUDENT_ID]

  send-degree:
    desc: Call the send-file endpoint
    cmds:
      - 'echo -n ''{"file": "{{.FILE_BASE64}}"}'' | http -b POST localhost:8099/students/{{.STUDENT_ID}}/files/abiturzeugnis ''X-API-KEY: This_is_a_test_APIKEY_with_30_chars+'' | jq'
    vars:
      FILE_BASE64:
        sh: "cat assets/Zeugnis.pdf | base64 -w 0"
    requires:
      vars: [STUDENT_ID]
